"""small changes 

Revision ID: afb881449ea8
Revises: f571f2458c2a
Create Date: 2022-01-07 12:41:34.419445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afb881449ea8'
down_revision = 'f571f2458c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
