name: { { cookiecutter.project } }
dependencies:
  - pandas=0.23.4
  - pytest=5.3.1
  - pytest-cov=2.8.1
  - numpy=1.17.4
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - pip:
      - azureml-sdk
      - joblib==0.14.1
      - matplotlib==3.1.2
      - scikit-learn==0.22.1
