cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip

stages:
  - docs

    # Deploy gitlab pages with documentation
pages:
  image: python:3.8-buster
  stage: docs
  script:
    - pip install -r mkdocs.txt
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
